# Generated by Django 3.1.2 on 2020-10-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('is_enable', models.BooleanField(verbose_name='Name')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['created_on'],
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
