# Generated by Django 3.1.2 on 2020-10-22 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20201022_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='is_enable',
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
