# Generated by Django 3.1.2 on 2020-10-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20201017_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='Subject'),
        ),
    ]
