# Generated by Django 3.1.2 on 2020-10-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20201018_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_on'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
